import { PrismaClient } from "@prisma/client";

function createPrismaClient() {
  const dbUrl = process.env.DATABASE_URL || "file:./dev.db";
  if (dbUrl.startsWith("postgresql") || dbUrl.startsWith("postgres://")) {
    const { PrismaPg } = require("@prisma/adapter-pg") as typeof import("@prisma/adapter-pg");
    const adapter = new PrismaPg({ connectionString: dbUrl });
    return new PrismaClient({ adapter });
  }
  const { PrismaLibSql } =
    require("@prisma/adapter-libsql") as typeof import("@prisma/adapter-libsql");
  const path = require("path");
  const filePath = dbUrl.replace("file:", "").trim();
  const absolutePath = path.resolve(filePath);
  const adapter = new PrismaLibSql({ url: `file://${absolutePath}` });
  return new PrismaClient({ adapter });
}

const prisma = createPrismaClient();

async function main() {
  const tanks = [
    { id: "PLD", name: "Paladin", role: "TANK" as const },
    { id: "WAR", name: "Warrior", role: "TANK" as const },
    { id: "DRK", name: "Dark Knight", role: "TANK" as const },
    { id: "GNB", name: "Gunbreaker", role: "TANK" as const },
  ];
  const healers = [
    { id: "WHM", name: "White Mage", role: "HEALER" as const },
    { id: "SCH", name: "Scholar", role: "HEALER" as const },
    { id: "AST", name: "Astrologian", role: "HEALER" as const },
    { id: "SGE", name: "Sage", role: "HEALER" as const },
  ];
  const melee = [
    { id: "MNK", name: "Monk", role: "MELEE" as const },
    { id: "DRG", name: "Dragoon", role: "MELEE" as const },
    { id: "NIN", name: "Ninja", role: "MELEE" as const },
    { id: "SAM", name: "Samurai", role: "MELEE" as const },
    { id: "RPR", name: "Reaper", role: "MELEE" as const },
    { id: "VPR", name: "Viper", role: "MELEE" as const },
  ];
  const ranged = [
    { id: "BRD", name: "Bard", role: "RANGED" as const },
    { id: "MCH", name: "Machinist", role: "RANGED" as const },
    { id: "DNC", name: "Dancer", role: "RANGED" as const },
  ];
  const caster = [
    { id: "BLM", name: "Black Mage", role: "CASTER" as const },
    { id: "SMN", name: "Summoner", role: "CASTER" as const },
    { id: "RDM", name: "Red Mage", role: "CASTER" as const },
    { id: "PCT", name: "Pictomancer", role: "CASTER" as const },
  ];

  const allJobs = [...tanks, ...healers, ...melee, ...ranged, ...caster];

  for (const job of allJobs) {
    await prisma.job.upsert({
      where: { id: job.id },
      update: { name: job.name, role: job.role },
      create: job,
    });
  }

  const abilities = [
    {
      name: "Reprisal",
      cooldown: 60,
      duration: 10,
      jobId: null,
      role: "TANK",
      category: "MITIGATION",
      sharedSlot: "REPRISAL",
      iconUrl: "https://xivapi.com/i/000000/000806.png",
    },
    {
      name: "Rampart",
      cooldown: 90,
      duration: 20,
      jobId: null,
      role: "TANK",
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000152.png",
    },
    {
      name: "Hallowed Ground",
      cooldown: 420,
      duration: 10,
      jobId: "PLD",
      role: null,
      category: "INVULN",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002502.png",
    },
    {
      name: "Sentinel",
      cooldown: 120,
      duration: 15,
      jobId: "PLD",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000151.png",
    },
    {
      name: "Divine Veil",
      cooldown: 90,
      duration: 30,
      jobId: "PLD",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002508.png",
    },
    {
      name: "Passage of Arms",
      cooldown: 120,
      duration: 18,
      jobId: "PLD",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002515.png",
    },
    {
      name: "Sheltron",
      cooldown: 5,
      duration: 4,
      jobId: "PLD",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002510.png",
    },
    {
      name: "Holmgang",
      cooldown: 420,
      duration: 10,
      jobId: "WAR",
      role: null,
      category: "INVULN",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000266.png",
    },
    {
      name: "Vengeance",
      cooldown: 120,
      duration: 15,
      jobId: "WAR",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000267.png",
    },
    {
      name: "Thrill of Battle",
      cooldown: 90,
      duration: 10,
      jobId: "WAR",
      role: null,
      category: "PERSONAL",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000263.png",
    },
    {
      name: "Shake It Off",
      cooldown: 90,
      duration: 30,
      jobId: "WAR",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002563.png",
    },
    {
      name: "Bloodwhetting",
      cooldown: 25,
      duration: 4,
      jobId: "WAR",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002569.png",
    },
    {
      name: "Living Dead",
      cooldown: 420,
      duration: 10,
      jobId: "DRK",
      role: null,
      category: "INVULN",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003077.png",
    },
    {
      name: "Shadow Wall",
      cooldown: 120,
      duration: 15,
      jobId: "DRK",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003075.png",
    },
    {
      name: "The Blackest Night",
      cooldown: 15,
      duration: 5,
      jobId: "DRK",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003081.png",
    },
    {
      name: "Dark Missionary",
      cooldown: 90,
      duration: 15,
      jobId: "DRK",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003087.png",
    },
    {
      name: "Oblation",
      cooldown: 30,
      duration: 5,
      jobId: "DRK",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003089.png",
    },
    {
      name: "Superbolide",
      cooldown: 420,
      duration: 10,
      jobId: "GNB",
      role: null,
      category: "INVULN",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003416.png",
    },
    {
      name: "Nebula",
      cooldown: 120,
      duration: 15,
      jobId: "GNB",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003412.png",
    },
    {
      name: "Heart of Corundum",
      cooldown: 25,
      duration: 4,
      jobId: "GNB",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003430.png",
    },
    {
      name: "Heart of Light",
      cooldown: 90,
      duration: 15,
      jobId: "GNB",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003424.png",
    },
    {
      name: "Benediction",
      cooldown: 180,
      duration: 0,
      jobId: "WHM",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002627.png",
    },
    {
      name: "Temperance",
      cooldown: 120,
      duration: 20,
      jobId: "WHM",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002645.png",
    },
    {
      name: "Divine Benison",
      cooldown: 30,
      duration: 15,
      jobId: "WHM",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002638.png",
    },
    {
      name: "Aquaveil",
      cooldown: 60,
      duration: 8,
      jobId: "WHM",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002648.png",
    },
    {
      name: "Lustrate",
      cooldown: 30,
      duration: 0,
      jobId: "SCH",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002805.png",
    },
    {
      name: "Adloquium",
      cooldown: 2,
      duration: 15,
      jobId: "SCH",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002801.png",
    },
    {
      name: "Succor",
      cooldown: 30,
      duration: 30,
      jobId: "SCH",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002802.png",
    },
    {
      name: "Deployment Tactics",
      cooldown: 90,
      duration: 0,
      jobId: "SCH",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002808.png",
    },
    {
      name: "Expedient",
      cooldown: 120,
      duration: 20,
      jobId: "SCH",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002878.png",
    },
    {
      name: "Protraction",
      cooldown: 60,
      duration: 10,
      jobId: "SCH",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002877.png",
    },
    {
      name: "Essential Dignity",
      cooldown: 40,
      duration: 0,
      jobId: "AST",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003141.png",
    },
    {
      name: "Neutral Sect",
      cooldown: 120,
      duration: 20,
      jobId: "AST",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003552.png",
    },
    {
      name: "Collective Unconscious",
      cooldown: 60,
      duration: 15,
      jobId: "AST",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003140.png",
    },
    {
      name: "Celestial Opposition",
      cooldown: 60,
      duration: 15,
      jobId: "AST",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003142.png",
    },
    {
      name: "Physis II",
      cooldown: 60,
      duration: 15,
      jobId: "SGE",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003670.png",
    },
    {
      name: "Kerachole",
      cooldown: 30,
      duration: 15,
      jobId: "SGE",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003666.png",
    },
    {
      name: "Taurochole",
      cooldown: 45,
      duration: 0,
      jobId: "SGE",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003671.png",
    },
    {
      name: "Holos",
      cooldown: 120,
      duration: 20,
      jobId: "SGE",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003678.png",
    },
    {
      name: "Panhaima",
      cooldown: 120,
      duration: 15,
      jobId: "SGE",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003679.png",
    },
    {
      name: "Haima",
      cooldown: 120,
      duration: 15,
      jobId: "SGE",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003673.png",
    },
    {
      name: "Mantra",
      cooldown: 90,
      duration: 15,
      jobId: "MNK",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000216.png",
    },
    {
      name: "Feint",
      cooldown: 120,
      duration: 15,
      jobId: null,
      role: "MELEE",
      category: "MITIGATION",
      sharedSlot: "FEINT",
      iconUrl: "https://xivapi.com/i/000000/000828.png",
    },
    {
      name: "Troubadour",
      cooldown: 90,
      duration: 15,
      jobId: "BRD",
      role: null,
      category: "MITIGATION",
      sharedSlot: "RANGED",
      iconUrl: "https://xivapi.com/i/002000/002612.png",
    },
    {
      name: "Nature's Minne",
      cooldown: 60,
      duration: 15,
      jobId: "BRD",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002615.png",
    },
    {
      name: "Tactician",
      cooldown: 90,
      duration: 15,
      jobId: "MCH",
      role: null,
      category: "MITIGATION",
      sharedSlot: "RANGED",
      iconUrl: "https://xivapi.com/i/003000/003040.png",
    },
    {
      name: "Shield Samba",
      cooldown: 90,
      duration: 15,
      jobId: "DNC",
      role: null,
      category: "MITIGATION",
      sharedSlot: "RANGED",
      iconUrl: "https://xivapi.com/i/003000/003469.png",
    },
    {
      name: "Addle",
      cooldown: 120,
      duration: 15,
      jobId: null,
      role: "CASTER",
      category: "MITIGATION",
      sharedSlot: "ADDLE",
      iconUrl: "https://xivapi.com/i/000000/000861.png",
    },
    {
      name: "Manaward",
      cooldown: 120,
      duration: 20,
      jobId: "BLM",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000463.png",
    },
    {
      name: "Magick Barrier",
      cooldown: 120,
      duration: 10,
      jobId: "RDM",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003237.png",
    },
    {
      name: "Tempera Grassa",
      cooldown: 120,
      duration: 20,
      jobId: "PCT",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003836.png",
    },
  ];

  for (const ability of abilities) {
    await prisma.ability.upsert({
      where: { id: ability.name },
      update: {
        cooldown: ability.cooldown,
        duration: ability.duration,
        jobId: ability.jobId,
        role: ability.role,
        category: ability.category as any,
        sharedSlot: ability.sharedSlot as any,
        iconUrl: ability.iconUrl,
      },
      create: {
        id: ability.name,
        name: ability.name,
        cooldown: ability.cooldown,
        duration: ability.duration,
        jobId: ability.jobId,
        role: ability.role,
        category: ability.category as any,
        sharedSlot: ability.sharedSlot as any,
        iconUrl: ability.iconUrl,
      },
    });
  }

  console.log("Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
