import { PrismaClient } from "@prisma/client";

function createPrismaClient() {
  const dbUrl = process.env.DATABASE_URL || "file:./dev.db";
  if (dbUrl.startsWith("postgresql") || dbUrl.startsWith("postgres://")) {
    const { PrismaPg } = require("@prisma/adapter-pg") as typeof import("@prisma/adapter-pg");
    const adapter = new PrismaPg({ connectionString: dbUrl });
    return new PrismaClient({ adapter });
  }
  const { PrismaLibSql } =
    require("@prisma/adapter-libsql") as typeof import("@prisma/adapter-libsql");
  const path = require("path");
  const filePath = dbUrl.replace("file:", "").trim();
  const absolutePath = path.resolve(filePath);
  const adapter = new PrismaLibSql({ url: `file://${absolutePath}` });
  return new PrismaClient({ adapter });
}

const prisma = createPrismaClient();

async function main() {
  const tanks = [
    { id: "PLD", name: "Paladin", role: "TANK" as const },
    { id: "WAR", name: "Warrior", role: "TANK" as const },
    { id: "DRK", name: "Dark Knight", role: "TANK" as const },
    { id: "GNB", name: "Gunbreaker", role: "TANK" as const },
  ];
  const healers = [
    { id: "WHM", name: "White Mage", role: "HEALER" as const },
    { id: "SCH", name: "Scholar", role: "HEALER" as const },
    { id: "AST", name: "Astrologian", role: "HEALER" as const },
    { id: "SGE", name: "Sage", role: "HEALER" as const },
  ];
  const melee = [
    { id: "MNK", name: "Monk", role: "MELEE" as const },
    { id: "DRG", name: "Dragoon", role: "MELEE" as const },
    { id: "NIN", name: "Ninja", role: "MELEE" as const },
    { id: "SAM", name: "Samurai", role: "MELEE" as const },
    { id: "RPR", name: "Reaper", role: "MELEE" as const },
    { id: "VPR", name: "Viper", role: "MELEE" as const },
  ];
  const ranged = [
    { id: "BRD", name: "Bard", role: "RANGED" as const },
    { id: "MCH", name: "Machinist", role: "RANGED" as const },
    { id: "DNC", name: "Dancer", role: "RANGED" as const },
  ];
  const caster = [
    { id: "BLM", name: "Black Mage", role: "CASTER" as const },
    { id: "SMN", name: "Summoner", role: "CASTER" as const },
    { id: "RDM", name: "Red Mage", role: "CASTER" as const },
    { id: "PCT", name: "Pictomancer", role: "CASTER" as const },
  ];

  const allJobs = [...tanks, ...healers, ...melee, ...ranged, ...caster];

  for (const job of allJobs) {
    await prisma.job.upsert({
      where: { id: job.id },
      update: { name: job.name, role: job.role },
      create: job,
    });
  }

  const abilities = [
    {
      name: "Reprisal",
      cooldown: 60,
      duration: 10,
      jobId: null,
      role: "TANK",
      category: "MITIGATION",
      sharedSlot: "REPRISAL",
      iconUrl: "https://xivapi.com/i/000000/000806.png",
    },
    {
      name: "Rampart",
      cooldown: 90,
      duration: 20,
      jobId: null,
      role: "TANK",
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000152.png",
    },
    {
      name: "Hallowed Ground",
      cooldown: 420,
      duration: 10,
      jobId: "PLD",
      role: null,
      category: "INVULN",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002502.png",
    },
    {
      name: "Sentinel",
      cooldown: 120,
      duration: 15,
      jobId: "PLD",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000151.png",
    },
    {
      name: "Divine Veil",
      cooldown: 90,
      duration: 30,
      jobId: "PLD",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002508.png",
    },
    {
      name: "Passage of Arms",
      cooldown: 120,
      duration: 18,
      jobId: "PLD",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002515.png",
    },
    {
      name: "Sheltron",
      cooldown: 5,
      duration: 4,
      jobId: "PLD",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002510.png",
    },
    {
      name: "Holmgang",
      cooldown: 420,
      duration: 10,
      jobId: "WAR",
      role: null,
      category: "INVULN",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000266.png",
    },
    {
      name: "Vengeance",
      cooldown: 120,
      duration: 15,
      jobId: "WAR",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000267.png",
    },
    {
      name: "Thrill of Battle",
      cooldown: 90,
      duration: 10,
      jobId: "WAR",
      role: null,
      category: "PERSONAL",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000263.png",
    },
    {
      name: "Shake It Off",
      cooldown: 90,
      duration: 30,
      jobId: "WAR",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002563.png",
    },
    {
      name: "Bloodwhetting",
      cooldown: 25,
      duration: 4,
      jobId: "WAR",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002569.png",
    },
    {
      name: "Living Dead",
      cooldown: 420,
      duration: 10,
      jobId: "DRK",
      role: null,
      category: "INVULN",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003077.png",
    },
    {
      name: "Shadow Wall",
      cooldown: 120,
      duration: 15,
      jobId: "DRK",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003075.png",
    },
    {
      name: "The Blackest Night",
      cooldown: 15,
      duration: 5,
      jobId: "DRK",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003081.png",
    },
    {
      name: "Dark Missionary",
      cooldown: 90,
      duration: 15,
      jobId: "DRK",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003087.png",
    },
    {
      name: "Oblation",
      cooldown: 30,
      duration: 5,
      jobId: "DRK",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003089.png",
    },
    {
      name: "Superbolide",
      cooldown: 420,
      duration: 10,
      jobId: "GNB",
      role: null,
      category: "INVULN",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003416.png",
    },
    {
      name: "Nebula",
      cooldown: 120,
      duration: 15,
      jobId: "GNB",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003412.png",
    },
    {
      name: "Heart of Corundum",
      cooldown: 25,
      duration: 4,
      jobId: "GNB",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003430.png",
    },
    {
      name: "Heart of Light",
      cooldown: 90,
      duration: 15,
      jobId: "GNB",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003424.png",
    },
    {
      name: "Benediction",
      cooldown: 180,
      duration: 0,
      jobId: "WHM",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002627.png",
    },
    {
      name: "Temperance",
      cooldown: 120,
      duration: 20,
      jobId: "WHM",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002645.png",
    },
    {
      name: "Divine Benison",
      cooldown: 30,
      duration: 15,
      jobId: "WHM",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002638.png",
    },
    {
      name: "Aquaveil",
      cooldown: 60,
      duration: 8,
      jobId: "WHM",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002648.png",
    },
    {
      name: "Lustrate",
      cooldown: 30,
      duration: 0,
      jobId: "SCH",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002805.png",
    },
    {
      name: "Adloquium",
      cooldown: 2,
      duration: 15,
      jobId: "SCH",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002801.png",
    },
    {
      name: "Succor",
      cooldown: 30,
      duration: 30,
      jobId: "SCH",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002802.png",
    },
    {
      name: "Deployment Tactics",
      cooldown: 90,
      duration: 0,
      jobId: "SCH",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002808.png",
    },
    {
      name: "Expedient",
      cooldown: 120,
      duration: 20,
      jobId: "SCH",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002878.png",
    },
    {
      name: "Protraction",
      cooldown: 60,
      duration: 10,
      jobId: "SCH",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002877.png",
    },
    {
      name: "Essential Dignity",
      cooldown: 40,
      duration: 0,
      jobId: "AST",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003141.png",
    },
    {
      name: "Neutral Sect",
      cooldown: 120,
      duration: 20,
      jobId: "AST",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003552.png",
    },
    {
      name: "Collective Unconscious",
      cooldown: 60,
      duration: 15,
      jobId: "AST",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003140.png",
    },
    {
      name: "Celestial Opposition",
      cooldown: 60,
      duration: 15,
      jobId: "AST",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003142.png",
    },
    {
      name: "Physis II",
      cooldown: 60,
      duration: 15,
      jobId: "SGE",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003670.png",
    },
    {
      name: "Kerachole",
      cooldown: 30,
      duration: 15,
      jobId: "SGE",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003666.png",
    },
    {
      name: "Taurochole",
      cooldown: 45,
      duration: 0,
      jobId: "SGE",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003671.png",
    },
    {
      name: "Holos",
      cooldown: 120,
      duration: 20,
      jobId: "SGE",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003678.png",
    },
    {
      name: "Panhaima",
      cooldown: 120,
      duration: 15,
      jobId: "SGE",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003679.png",
    },
    {
      name: "Haima",
      cooldown: 120,
      duration: 15,
      jobId: "SGE",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003673.png",
    },
    {
      name: "Mantra",
      cooldown: 90,
      duration: 15,
      jobId: "MNK",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000216.png",
    },
    {
      name: "Feint",
      cooldown: 120,
      duration: 15,
      jobId: null,
      role: "MELEE",
      category: "MITIGATION",
      sharedSlot: "FEINT",
      iconUrl: "https://xivapi.com/i/000000/000828.png",
    },
    {
      name: "Troubadour",
      cooldown: 90,
      duration: 15,
      jobId: "BRD",
      role: null,
      category: "MITIGATION",
      sharedSlot: "RANGED",
      iconUrl: "https://xivapi.com/i/002000/002612.png",
    },
    {
      name: "Nature's Minne",
      cooldown: 60,
      duration: 15,
      jobId: "BRD",
      role: null,
      category: "HEALING",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/002000/002615.png",
    },
    {
      name: "Tactician",
      cooldown: 90,
      duration: 15,
      jobId: "MCH",
      role: null,
      category: "MITIGATION",
      sharedSlot: "RANGED",
      iconUrl: "https://xivapi.com/i/003000/003040.png",
    },
    {
      name: "Shield Samba",
      cooldown: 90,
      duration: 15,
      jobId: "DNC",
      role: null,
      category: "MITIGATION",
      sharedSlot: "RANGED",
      iconUrl: "https://xivapi.com/i/003000/003469.png",
    },
    {
      name: "Addle",
      cooldown: 120,
      duration: 15,
      jobId: null,
      role: "CASTER",
      category: "MITIGATION",
      sharedSlot: "ADDLE",
      iconUrl: "https://xivapi.com/i/000000/000861.png",
    },
    {
      name: "Manaward",
      cooldown: 120,
      duration: 20,
      jobId: "BLM",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/000000/000463.png",
    },
    {
      name: "Magick Barrier",
      cooldown: 120,
      duration: 10,
      jobId: "RDM",
      role: null,
      category: "MITIGATION",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003237.png",
    },
    {
      name: "Tempera Grassa",
      cooldown: 120,
      duration: 20,
      jobId: "PCT",
      role: null,
      category: "SHIELD",
      sharedSlot: null,
      iconUrl: "https://xivapi.com/i/003000/003836.png",
    },
  ];

  for (const ability of abilities) {
    await prisma.ability.upsert({
      where: { id: ability.name },
      update: {
        cooldown: ability.cooldown,
        duration: ability.duration,
        jobId: ability.jobId,
        role: ability.role,
        category: ability.category as any,
        sharedSlot: ability.sharedSlot as any,
        iconUrl: ability.iconUrl,
      },
      create: {
        id: ability.name,
        name: ability.name,
        cooldown: ability.cooldown,
        duration: ability.duration,
        jobId: ability.jobId,
        role: ability.role,
        category: ability.category as any,
        sharedSlot: ability.sharedSlot as any,
        iconUrl: ability.iconUrl,
      },
    });
  }

  const fights = [
    // ── AAC Light-heavyweight (Savage) ──────────────────────
    {
      slug: "m1s",
      name: "M1S - Black Cat",
      patch: "7.05",
      bossName: "Black Cat",
      expansion: "Dawntrail",
      tier: "AAC Light-heavyweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 7, label: "Predaceous Pounce", type: "TANKBUSTER" },
        { time: 17, label: "Quadruple Crossing #1", type: "RAIDWIDE" },
        { time: 25, label: "Quadruple Crossing #2", type: "RAIDWIDE" },
        { time: 33, label: "Quadruple Crossing #3", type: "RAIDWIDE" },
        { time: 39, label: "Quadruple Crossing #4", type: "RAIDWIDE" },
        { time: 47, label: "Overshadow", type: "OTHER" },
        { time: 57, label: "Biscuit Maker", type: "TANKBUSTER" },
        { time: 68, label: "Elevate and Eviscerate", type: "RAIDWIDE" },
        { time: 82, label: "One-Two Punch", type: "TANKBUSTER" },
        { time: 93, label: "Nine Lives", type: "RAIDWIDE" },
        { time: 105, label: "Overshadow", type: "OTHER" },
        { time: 113, label: "Grim Embrace", type: "TANKBUSTER" },
        { time: 119, label: "Black Cat's Crossing #1", type: "STACK" },
        { time: 126, label: "Black Cat's Crossing #2", type: "STACK" },
        { time: 133, label: "Black Cat's Crossing #3", type: "STACK" },
        { time: 139, label: "Black Cat's Crossing #4", type: "STACK" },
        { time: 155, label: "One-Two Punch", type: "TANKBUSTER" },
        { time: 170, label: "Elevate and Eviscerate", type: "RAIDWIDE" },
        { time: 195, label: "Don't Cross the Cat", type: "OTHER" },
        { time: 202, label: "Biscuit Maker", type: "TANKBUSTER" },
        { time: 220, label: "Finale", type: "ENRAGE" },
      ],
    },
    {
      slug: "m2s",
      name: "M2S - Honey B. Lovely",
      patch: "7.05",
      bossName: "Honey B. Lovely",
      expansion: "Dawntrail",
      tier: "AAC Light-heavyweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 8, label: "Splash of Venom", type: "SPREAD" },
        { time: 17, label: "Honey Behemoth", type: "ADD_PHASE" },
        { time: 25, label: "Honeyed Breeze", type: "RAIDWIDE" },
        { time: 32, label: "Blinding Love", type: "STACK" },
        { time: 55, label: "Honey Behemoth", type: "ADD_PHASE" },
        { time: 63, label: "Honeyed Breeze", type: "RAIDWIDE" },
        { time: 70, label: "Blinding Love", type: "STACK" },
        { time: 93, label: "Tempting Twist", type: "TANKBUSTER" },
        { time: 105, label: "Splash of Venom", type: "SPREAD" },
        { time: 118, label: "Honey Behemoth", type: "ADD_PHASE" },
        { time: 126, label: "Honeyed Breeze", type: "RAIDWIDE" },
        { time: 132, label: "Blinding Love", type: "STACK" },
        { time: 147, label: "Kiss of Oblivion + Love Me Tender", type: "TANKBUSTER" },
        { time: 163, label: "Love Me Tender x3", type: "RAIDWIDE" },
        { time: 178, label: "Splash of Venom", type: "SPREAD" },
        { time: 191, label: "Honeyed Breeze", type: "RAIDWIDE" },
        { time: 203, label: "Finale", type: "ENRAGE" },
      ],
    },
    {
      slug: "m3s",
      name: "M3S - Brute Bomber",
      patch: "7.05",
      bossName: "Brute Bomber",
      expansion: "Dawntrail",
      tier: "AAC Light-heavyweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 6, label: "Left/Right Punch", type: "TANKBUSTER" },
        { time: 20, label: "Screwdriver", type: "OTHER" },
        { time: 28, label: "Chain Death", type: "RAIDWIDE" },
        { time: 42, label: "Explosion", type: "OTHER" },
        { time: 58, label: "Double Punch", type: "TANKBUSTER" },
        { time: 73, label: "Screwdriver", type: "OTHER" },
        { time: 81, label: "Chain Death", type: "RAIDWIDE" },
        { time: 92, label: "Bomber's Fury", type: "RAIDWIDE" },
        { time: 101, label: "Raging Claw #1", type: "STACK" },
        { time: 107, label: "Raging Claw #2", type: "STACK" },
        { time: 114, label: "Raging Claw #3", type: "STACK" },
        { time: 121, label: "Screwdriver", type: "OTHER" },
        { time: 132, label: "Explosion", type: "OTHER" },
        { time: 144, label: "Final Beat", type: "RAIDWIDE" },
        { time: 156, label: "Screwdriver", type: "OTHER" },
        { time: 166, label: "Chain Death", type: "RAIDWIDE" },
        { time: 180, label: "Screwdriver", type: "OTHER" },
        { time: 190, label: "Final Beat", type: "RAIDWIDE" },
        { time: 196, label: "Finale", type: "ENRAGE" },
      ],
    },
    {
      slug: "m4s",
      name: "M4S - Wicked Thunder",
      patch: "7.05",
      bossName: "Wicked Thunder",
      expansion: "Dawntrail",
      tier: "AAC Light-heavyweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 11, label: "Thunderous Kick", type: "TANKBUSTER" },
        { time: 23, label: "Forked Lightning", type: "RAIDWIDE" },
        { time: 36, label: "Wicked Bolt", type: "STACK" },
        { time: 48, label: "Forked Lightning", type: "RAIDWIDE" },
        { time: 63, label: "Electrocharge #1", type: "OTHER" },
        { time: 71, label: "Electrocharge #2", type: "OTHER" },
        { time: 80, label: "Beast's Bane", type: "TANKBUSTER" },
        { time: 93, label: "Forked Lightning", type: "RAIDWIDE" },
        { time: 108, label: "Wicked Bolt", type: "STACK" },
        { time: 118, label: "Forked Lightning", type: "RAIDWIDE" },
        { time: 132, label: "Electrocharge #1", type: "OTHER" },
        { time: 141, label: "Electrocharge #2", type: "OTHER" },
        { time: 150, label: "Soul Surge", type: "SPREAD" },
        { time: 167, label: "Wrath of Thunder", type: "RAIDWIDE" },
        { time: 175, label: "Wicked Bolt", type: "STACK" },
        { time: 185, label: "Forked Lightning", type: "RAIDWIDE" },
        { time: 199, label: "Electrocharge #1", type: "OTHER" },
        { time: 207, label: "Electrocharge #2", type: "OTHER" },
        { time: 215, label: "Wicked Thunder", type: "RAIDWIDE" },
        { time: 234, label: "Thunderous Kick", type: "TANKBUSTER" },
        { time: 257, label: "Finale", type: "ENRAGE" },
      ],
    },
    // ── AAC Cruiserweight (Savage) ──────────────────────────
    {
      slug: "m5s",
      name: "M5S - Dancing Green",
      patch: "7.2",
      bossName: "Dancing Green",
      expansion: "Dawntrail",
      tier: "AAC Cruiserweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 10, label: "Disco Inferno", type: "RAIDWIDE" },
        { time: 20, label: "Soaring Minx", type: "ADD_PHASE" },
        { time: 31, label: "Ensemble Assemble", type: "STACK" },
        { time: 39, label: "Ride the Waves #1", type: "SPREAD" },
        { time: 47, label: "Ride the Waves #2", type: "SPREAD" },
        { time: 58, label: "Geyser", type: "OTHER" },
        { time: 65, label: "Frogtourage", type: "ADD_PHASE" },
        { time: 78, label: "Disco Inferno", type: "RAIDWIDE" },
        { time: 87, label: "Ensemble Assemble", type: "STACK" },
        { time: 98, label: "Ride the Waves #1", type: "SPREAD" },
        { time: 109, label: "Ride the Waves #2", type: "SPREAD" },
        { time: 118, label: "Frogtourage", type: "ADD_PHASE" },
        { time: 136, label: "Disco Inferno", type: "RAIDWIDE" },
        { time: 146, label: "Soaring Minx", type: "ADD_PHASE" },
        { time: 155, label: "Ensemble Assemble", type: "STACK" },
        { time: 163, label: "Ride the Waves #1", type: "SPREAD" },
        { time: 170, label: "Ride the Waves #2", type: "SPREAD" },
        { time: 183, label: "Geyser", type: "OTHER" },
        { time: 190, label: "Frogtourage", type: "ADD_PHASE" },
        { time: 208, label: "Disco Inferno", type: "RAIDWIDE" },
        { time: 218, label: "Finale", type: "ENRAGE" },
      ],
    },
    {
      slug: "m6s",
      name: "M6S - Sugar Riot",
      patch: "7.2",
      bossName: "Sugar Riot",
      expansion: "Dawntrail",
      tier: "AAC Cruiserweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 10, label: "Sugar Shock", type: "RAIDWIDE" },
        { time: 19, label: "Candy Crush", type: "TANKBUSTER" },
        { time: 30, label: "Sweet Tooth", type: "STACK" },
        { time: 37, label: "Lives a Gummy #1", type: "OTHER" },
        { time: 44, label: "Lives a Gummy #2", type: "OTHER" },
        { time: 52, label: "Sugar Shock", type: "RAIDWIDE" },
        { time: 60, label: "Candy Crush", type: "TANKBUSTER" },
        { time: 72, label: "Sweet Tooth", type: "STACK" },
        { time: 79, label: "Lives a Gummy #1", type: "OTHER" },
        { time: 86, label: "Lives a Gummy #2", type: "OTHER" },
        { time: 96, label: "Super Sweet + Stack", type: "STACK" },
        { time: 106, label: "Cherry Bomb", type: "OTHER" },
        { time: 118, label: "Sugar Shock", type: "RAIDWIDE" },
        { time: 127, label: "Riot Rush + Spread", type: "SPREAD" },
        { time: 137, label: "Syllogism", type: "OTHER" },
        { time: 143, label: "Syllogism", type: "OTHER" },
        { time: 148, label: "Syllogism", type: "OTHER" },
        { time: 157, label: "Riot Rush + Spread", type: "SPREAD" },
        { time: 167, label: "Sugar Shock", type: "RAIDWIDE" },
        { time: 178, label: "Super Sweet + Stack", type: "STACK" },
        { time: 193, label: "Candy Crush", type: "TANKBUSTER" },
        { time: 204, label: "Sugar Shock", type: "RAIDWIDE" },
        { time: 220, label: "Finale", type: "ENRAGE" },
      ],
    },
    {
      slug: "m7s",
      name: "M7S - Brute Abombinator",
      patch: "7.2",
      bossName: "Brute Abombinator",
      expansion: "Dawntrail",
      tier: "AAC Cruiserweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 5, label: "Brutal Impact", type: "RAIDWIDE" },
        { time: 10, label: "Stoneringer", type: "TANKBUSTER" },
        { time: 17, label: "Smash Here/There #1", type: "STACK" },
        { time: 23, label: "Smash Here/There #2", type: "STACK" },
        { time: 33, label: "Sinister Seeds", type: "ADD_PHASE" },
        { time: 42, label: "Brutal Impact", type: "RAIDWIDE" },
        { time: 50, label: "Stoneringer", type: "TANKBUSTER" },
        { time: 65, label: "Smash Here/There #1", type: "SPREAD" },
        { time: 71, label: "Smash Here/There #2", type: "SPREAD" },
        { time: 85, label: "Sinister Seeds", type: "ADD_PHASE" },
        { time: 96, label: "Brutal Impact", type: "RAIDWIDE" },
        { time: 108, label: "Neo Stoneringer", type: "TANKBUSTER" },
        { time: 118, label: "Smash Bad/Good", type: "OTHER" },
        { time: 126, label: "Brutal Impact", type: "RAIDWIDE" },
        { time: 135, label: "Sinister Seeds", type: "ADD_PHASE" },
        { time: 145, label: "Brutal Impact", type: "RAIDWIDE" },
        { time: 154, label: "Neo Stoneringer", type: "TANKBUSTER" },
        { time: 170, label: "Smash Bad/Good", type: "OTHER" },
        { time: 175, label: "Smash Bad/Good", type: "OTHER" },
        { time: 185, label: "Brutal Impact", type: "RAIDWIDE" },
        { time: 196, label: "Sinister Germs", type: "OTHER" },
        { time: 206, label: "Brutal Impact", type: "RAIDWIDE" },
        { time: 213, label: "Finale", type: "ENRAGE" },
      ],
    },
    {
      slug: "m8s",
      name: "M8S - Howling Blade",
      patch: "7.2",
      bossName: "Howling Blade",
      expansion: "Dawntrail",
      tier: "AAC Cruiserweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 3, label: "Stonefang", type: "TANKBUSTER" },
        { time: 10, label: "Windfang", type: "RAIDWIDE" },
        { time: 21, label: "Bogged Down #1", type: "OTHER" },
        { time: 27, label: "Bogged Down #2", type: "OTHER" },
        { time: 32, label: "Bogged Down #3", type: "OTHER" },
        { time: 44, label: "Millennial Decay", type: "STACK" },
        { time: 56, label: "Bogged Down #1", type: "OTHER" },
        { time: 60, label: "Bogged Down #2", type: "OTHER" },
        { time: 66, label: "Bogged Down #3", type: "OTHER" },
        { time: 78, label: "Ravenous Saber", type: "TANKBUSTER" },
        { time: 87, label: "Windfang", type: "RAIDWIDE" },
        { time: 101, label: "Wolves' Reign #1", type: "ADD_PHASE" },
        { time: 107, label: "Wolves' Reign #2", type: "ADD_PHASE" },
        { time: 113, label: "Wolves' Reign #3", type: "ADD_PHASE" },
        { time: 122, label: "Windfang", type: "RAIDWIDE" },
        { time: 130, label: "Terrestrial Titans #1", type: "OTHER" },
        { time: 136, label: "Terrestrial Titans #2", type: "OTHER" },
        { time: 145, label: "Stonefang", type: "TANKBUSTER" },
        { time: 153, label: "Windfang", type: "RAIDWIDE" },
        { time: 162, label: "Blade of the Grave #1", type: "OTHER" },
        { time: 170, label: "Blade of the Grave #2", type: "OTHER" },
        { time: 178, label: "Blade of the Grave #3", type: "OTHER" },
        { time: 185, label: "Blade of the Grave #4", type: "OTHER" },
        { time: 196, label: "Windfang", type: "RAIDWIDE" },
        { time: 208, label: "Battle of the Bards #1", type: "OTHER" },
        { time: 212, label: "Battle of the Bards #2", type: "OTHER" },
        { time: 218, label: "Battle of the Bards #3", type: "OTHER" },
        { time: 224, label: "Battle of the Bards #4", type: "OTHER" },
        { time: 233, label: "Windfang", type: "RAIDWIDE" },
        { time: 241, label: "Millennial Decay", type: "STACK" },
        { time: 253, label: "Stormfang", type: "OTHER" },
        { time: 260, label: "Phase Change", type: "OTHER" },
        { time: 270, label: "Soul of the Howling Blade", type: "OTHER" },
        { time: 283, label: "Wolves' Reign #1", type: "ADD_PHASE" },
        { time: 289, label: "Wolves' Reign #2", type: "ADD_PHASE" },
        { time: 295, label: "Wolves' Reign #3", type: "ADD_PHASE" },
        { time: 306, label: "Windfang", type: "RAIDWIDE" },
        { time: 322, label: "Millennial Decay", type: "STACK" },
        { time: 336, label: "Wolves' Reign #1", type: "ADD_PHASE" },
        { time: 342, label: "Wolves' Reign #2", type: "ADD_PHASE" },
        { time: 348, label: "Wolves' Reign #3", type: "ADD_PHASE" },
        { time: 355, label: "Blade of the Grave #1", type: "OTHER" },
        { time: 361, label: "Blade of the Grave #2", type: "OTHER" },
        { time: 366, label: "Blade of the Grave #3", type: "OTHER" },
        { time: 372, label: "Blade of the Grave #4", type: "OTHER" },
        { time: 382, label: "Windfang", type: "RAIDWIDE" },
        { time: 395, label: "Soul of the Howling Blade + Windfang", type: "RAIDWIDE" },
        { time: 410, label: "Finale", type: "ENRAGE" },
      ],
    },
    // ── AAC Heavyweight (Savage) ────────────────────────────
    {
      slug: "m9s",
      name: "M9S - Vamp Fatale",
      patch: "7.4",
      bossName: "Vamp Fatale",
      expansion: "Dawntrail",
      tier: "AAC Heavyweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 6, label: "Killer Voice", type: "RAIDWIDE" },
        { time: 12, label: "Hardcore", type: "TANKBUSTER" },
        { time: 27, label: "Half Moon", type: "SPREAD" },
        { time: 35, label: "Half Moon", type: "SPREAD" },
        { time: 50, label: "Tower of Magic", type: "OTHER" },
        { time: 60, label: "Tower of Magic", type: "OTHER" },
        { time: 68, label: "Sadistic Screech", type: "RAIDWIDE" },
        { time: 80, label: "Vamp Stomp #1", type: "STACK" },
        { time: 87, label: "Vamp Stomp #2", type: "STACK" },
        { time: 92, label: "Vamp Stomp #3", type: "STACK" },
        { time: 100, label: "Killer Voice", type: "RAIDWIDE" },
        { time: 108, label: "Hardcore", type: "TANKBUSTER" },
        { time: 132, label: "Curtain Call #1", type: "RAIDWIDE" },
        { time: 147, label: "Curtain Call #2", type: "RAIDWIDE" },
        { time: 165, label: "Vampette #1", type: "ADD_PHASE" },
        { time: 170, label: "Vampette #2", type: "ADD_PHASE" },
        { time: 180, label: "Killer Voice", type: "RAIDWIDE" },
        { time: 188, label: "Hardcore", type: "TANKBUSTER" },
        { time: 210, label: "Sadistic Screech", type: "RAIDWIDE" },
        { time: 222, label: "Half Moon", type: "SPREAD" },
        { time: 229, label: "Half Moon", type: "SPREAD" },
        { time: 235, label: "Curtain Call #1", type: "RAIDWIDE" },
        { time: 244, label: "Curtain Call #2", type: "RAIDWIDE" },
        { time: 255, label: "Finale", type: "ENRAGE" },
      ],
    },
    {
      slug: "m10s",
      name: "M10S - Red Hot & Deep Blue",
      patch: "7.4",
      bossName: "The Xtremes",
      expansion: "Dawntrail",
      tier: "AAC Heavyweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 7, label: "Inferno + Deep Blue", type: "RAIDWIDE" },
        { time: 15, label: "Alley-oop G #1", type: "RAIDWIDE" },
        { time: 22, label: "Alley-oop G #2", type: "RAIDWIDE" },
        { time: 31, label: "Steam Burst", type: "OTHER" },
        { time: 40, label: "Alley-oop G #3", type: "RAIDWIDE" },
        { time: 47, label: "Alley-oop G #4", type: "RAIDWIDE" },
        { time: 57, label: "High Jump/Ground Dash #1", type: "TANKBUSTER" },
        { time: 74, label: "Alley-oop Inferno", type: "RAIDWIDE" },
        { time: 81, label: "Alley-oop Reverse", type: "RAIDWIDE" },
        { time: 95, label: "Epic Water + Fire", type: "STACK" },
        { time: 99, label: "Epic Water + Fire", type: "STACK" },
        { time: 103, label: "Epic Water + Fire", type: "STACK" },
        { time: 107, label: "Epic Water + Fire", type: "STACK" },
        { time: 115, label: "High Jump/Ground Dash #2", type: "TANKBUSTER" },
        { time: 125, label: "Cutback Blaze", type: "OTHER" },
        { time: 133, label: "Burning Mural", type: "OTHER" },
        { time: 145, label: "Pyrotation #1", type: "OTHER" },
        { time: 152, label: "Pyrotation #2", type: "OTHER" },
        { time: 160, label: "Pyrotation #3", type: "OTHER" },
        { time: 167, label: "Pyrotation #4", type: "OTHER" },
        { time: 175, label: "Pyrotation #5 + Deep Impact", type: "TANKBUSTER" },
        { time: 187, label: "Alley-oop Inferno", type: "RAIDWIDE" },
        { time: 194, label: "Alley-oop Reverse", type: "RAIDWIDE" },
        { time: 200, label: "Epic Water + Fire", type: "STACK" },
        { time: 204, label: "Epic Water + Fire", type: "STACK" },
        { time: 208, label: "Epic Water + Fire", type: "STACK" },
        { time: 212, label: "Epic Water + Fire", type: "STACK" },
        { time: 222, label: "Burning Mural + Burn...", type: "OTHER" },
        { time: 230, label: "Burn, Baby, Burn #1", type: "OTHER" },
        { time: 238, label: "Burn, Baby, Burn #2", type: "OTHER" },
        { time: 245, label: "Burn, Baby, Burn #3", type: "OTHER" },
        { time: 252, label: "Burn, Baby, Burn #4", type: "OTHER" },
        { time: 262, label: "Alley-oop Inferno", type: "RAIDWIDE" },
        { time: 269, label: "Alley-oop Reverse", type: "RAIDWIDE" },
        { time: 277, label: "Burning Mural", type: "OTHER" },
        { time: 287, label: "Deep Impact", type: "TANKBUSTER" },
        { time: 299, label: "Deep Blue", type: "RAIDWIDE" },
        { time: 316, label: "Sickest Take-off #1", type: "OTHER" },
        { time: 323, label: "Sickest Take-off #2", type: "OTHER" },
        { time: 330, label: "Sickest Take-off #3", type: "OTHER" },
        { time: 338, label: "Sickest Take-off #4", type: "OTHER" },
        { time: 345, label: "Sickest Take-off #5", type: "OTHER" },
        { time: 350, label: "Deep Blue", type: "RAIDWIDE" },
        { time: 359, label: "High Jump/Ground Dash #3", type: "TANKBUSTER" },
        { time: 371, label: "Pyrotation #1", type: "OTHER" },
        { time: 378, label: "Pyrotation #2", type: "OTHER" },
        { time: 385, label: "Pyrotation #3", type: "OTHER" },
        { time: 392, label: "Pyrotation #4", type: "OTHER" },
        { time: 399, label: "Pyrotation #5 + Deep Impact", type: "TANKBUSTER" },
        { time: 411, label: "Alley-oop Inferno", type: "RAIDWIDE" },
        { time: 418, label: "Alley-oop Reverse", type: "RAIDWIDE" },
        { time: 421, label: "Alley-oop Inferno", type: "RAIDWIDE" },
        { time: 426, label: "Alley-oop Double/Reverse #1", type: "RAIDWIDE" },
        { time: 434, label: "Alley-oop Double/Reverse #2", type: "RAIDWIDE" },
        { time: 434, label: "Sickest Take-off", type: "RAIDWIDE" },
        { time: 436, label: "Steam Burst", type: "OTHER" },
        { time: 439, label: "Freaky Pyrotation+Steam Burst", type: "SPREAD" },
        { time: 447, label: "Sick Swell Hit", type: "RAIDWIDE" },
        { time: 449, label: "Divers' Dare x2", type: "SPREAD" },
        { time: 450, label: "Awesome AoE", type: "OTHER" },
        { time: 451, label: "Steam Burst", type: "OTHER" },
        { time: 463, label: "Epic Brotherhood", type: "RAIDWIDE" },
        { time: 465, label: "Extreme Fire/Watersnaking", type: "RAIDWIDE" },
        { time: 478, label: "Insane Air + Bailout #1", type: "OTHER" },
        { time: 489, label: "Insane Air + Bailout #2", type: "OTHER" },
        { time: 499, label: "Insane Air + Bailout #3", type: "OTHER" },
        { time: 509, label: "Insane Air + Bailout #4", type: "OTHER" },
        { time: 524, label: "Divers' Dare x2", type: "SPREAD" },
        { time: 535, label: "Epic Brotherhood", type: "RAIDWIDE" },
        { time: 540, label: "Alley-oop Double/Reverse #1", type: "RAIDWIDE" },
        { time: 547, label: "Alley-oop Inferno", type: "RAIDWIDE" },
        { time: 548, label: "Alley-oop Double/Reverse #2", type: "RAIDWIDE" },
        { time: 551, label: "Pyrotation + Deep Impact", type: "TANKBUSTER" },
        { time: 552, label: "Steam Burst", type: "OTHER" },
        { time: 565, label: "Divers' Dare x2", type: "SPREAD" },
        { time: 574, label: "Divers' Dare x2", type: "SPREAD" },
        { time: 591, label: "Over the Falls", type: "OTHER" },
      ],
    },
    {
      slug: "m11s",
      name: "M11S - The Tyrant",
      patch: "7.4",
      bossName: "The Tyrant",
      expansion: "Dawntrail",
      tier: "AAC Heavyweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 5, label: "Crown of Arcadia", type: "RAIDWIDE" },
        { time: 15, label: "Raw Steel Trophy", type: "RAIDWIDE" },
        { time: 25, label: "Raw Steel", type: "RAIDWIDE" },
        { time: 35, label: "Trophy Weapons", type: "RAIDWIDE" },
        { time: 41, label: "Assault Evolved", type: "RAIDWIDE" },
        { time: 50, label: "Assault Evolved #1", type: "RAIDWIDE" },
        { time: 60, label: "Assault Evolved #3", type: "RAIDWIDE" },
        { time: 69, label: "Trophy Weapons", type: "RAIDWIDE" },
        { time: 75, label: "Void Stardust", type: "OTHER" },
        { time: 83, label: "Void Stardust Baits x3", type: "OTHER" },
        { time: 87, label: "Assault Evolved", type: "RAIDWIDE" },
        { time: 95, label: "Assault Evolved #1", type: "RAIDWIDE" },
        { time: 110, label: "Void Stardust Baits x3", type: "OTHER" },
        { time: 117, label: "Crown of Arcadia", type: "RAIDWIDE" },
        { time: 135, label: "Dance of Domination Trophy", type: "RAIDWIDE" },
        { time: 141, label: "Dance of Domination Trophy Hits", type: "RAIDWIDE" },
        { time: 155, label: "Raw Steel Trophy", type: "RAIDWIDE" },
        { time: 174, label: "Charybdistopia", type: "OTHER" },
        { time: 182, label: "Ultimate Trophy Weapons", type: "RAIDWIDE" },
        { time: 188, label: "Assault Apex", type: "OTHER" },
        { time: 195, label: "Assault Evolved #1", type: "RAIDWIDE" },
        { time: 200, label: "Assault Evolved #2", type: "RAIDWIDE" },
        { time: 205, label: "Assault Evolved #3", type: "RAIDWIDE" },
        { time: 210, label: "Assault Evolved #4", type: "RAIDWIDE" },
        { time: 232, label: "One and Only", type: "OTHER" },
        { time: 248, label: "Great Wall of Fire #1", type: "OTHER" },
        { time: 257, label: "Great Wall of Fire #2 + Line Dodge", type: "OTHER" },
        { time: 260, label: "Line Dodge", type: "OTHER" },
        { time: 262, label: "Orbital Omen", type: "RAIDWIDE" },
        { time: 271, label: "Fire and Fury", type: "RAIDWIDE" },
        { time: 288, label: "Meteorain", type: "OTHER" },
        { time: 296, label: "Fearsome Fireball + Cosmic Kiss #1", type: "RAIDWIDE" },
        { time: 305, label: "Fearsome Fireball + Cosmic Kiss #2", type: "RAIDWIDE" },
        { time: 310, label: "Foregone Fatality #1", type: "OTHER" },
        { time: 315, label: "Fearsome Fireball + Cosmic Kiss #3", type: "RAIDWIDE" },
        { time: 325, label: "Fearsome Fireball", type: "RAIDWIDE" },
        { time: 330, label: "Foregone Fatality #2", type: "OTHER" },
        { time: 336, label: "Triple Tyrannihilation", type: "OTHER" },
        { time: 357, label: "Flatliner", type: "TANKBUSTER" },
        { time: 372, label: "Majestic Meteor", type: "OTHER" },
        { time: 396, label: "Majestic Meteowrath + Fire Breath", type: "OTHER" },
        { time: 428, label: "Majestic Meteowrath + Fire Breath", type: "OTHER" },
        { time: 433, label: "Meteor Baits x3", type: "OTHER" },
        { time: 441, label: "Massive Meteor", type: "OTHER" },
        { time: 455, label: "Arcadian Avalanche Hit", type: "OTHER" },
        { time: 476, label: "Crown of Arcadia", type: "RAIDWIDE" },
        { time: 488, label: "Great Wall of Fire #1", type: "OTHER" },
        { time: 496, label: "Great Wall of Fire #2 + Line Dodge", type: "OTHER" },
        { time: 500, label: "Line Dodge", type: "OTHER" },
        { time: 501, label: "Orbital Omen", type: "RAIDWIDE" },
        { time: 511, label: "Fire and Fury", type: "RAIDWIDE" },
        { time: 519, label: "Crown of Arcadia", type: "RAIDWIDE" },
        { time: 531, label: "Ecliptic Stampede", type: "RAIDWIDE" },
        { time: 560, label: "Ecliptic Towers", type: "RAIDWIDE" },
        { time: 567, label: "Two/Fourway Fireball", type: "OTHER" },
        { time: 569, label: "Majestic Meteowrath", type: "OTHER" },
        { time: 577, label: "Crown of Arcadia", type: "RAIDWIDE" },
        { time: 590, label: "Heartbreak Kick x5", type: "TANKBUSTER" },
        { time: 609, label: "Heartbreak Kick x6", type: "TANKBUSTER" },
        { time: 630, label: "Heartbreak Kick x7", type: "TANKBUSTER" },
        { time: 654, label: "Heartbreaker", type: "OTHER" },
      ],
    },
    {
      slug: "m12s",
      name: "M12S - Lindwurm",
      patch: "7.4",
      bossName: "Lindwurm",
      expansion: "Dawntrail",
      tier: "AAC Heavyweight",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 10, label: "The Fixer", type: "RAIDWIDE" },
        { time: 29, label: "Mortal Slayer #1", type: "TANKBUSTER" },
        { time: 67, label: "Grotesquerie: Act 1", type: "STACK" },
        { time: 97, label: "Burst+Fourth-Wall Fusion+Visceral Burst", type: "OTHER" },
        { time: 102, label: "The Fixer", type: "RAIDWIDE" },
        { time: 117, label: "Grotesquerie: Act 2", type: "STACK" },
        { time: 132, label: "Cruel Coil", type: "OTHER" },
        { time: 141, label: "Skinsplitter", type: "OTHER" },
        { time: 146, label: "Skinsplitter", type: "OTHER" },
        { time: 151, label: "Skinsplitter", type: "OTHER" },
        { time: 161, label: "Skinsplitter", type: "OTHER" },
        { time: 171, label: "Skinsplitter Final", type: "OTHER" },
        { time: 183, label: "Splattershed", type: "RAIDWIDE" },
        { time: 203, label: "Grotesquerie: Act 3", type: "STACK" },
        { time: 216, label: "Bring Down the House", type: "OTHER" },
        { time: 236, label: "The Fixer", type: "RAIDWIDE" },
        { time: 240, label: "Phase Change", type: "OTHER" },
        { time: 250, label: "Grotesquerie: Curtain Call", type: "STACK" },
        { time: 250, label: "Arcadia Aflame", type: "RAIDWIDE" },
        { time: 257, label: "Phagocyte Spotlight x5", type: "OTHER" },
        { time: 265, label: "Replication I", type: "RAIDWIDE" },
        { time: 276, label: "Winged Scourge+Top-tier Slam+Mighty Magic", type: "OTHER" },
        { time: 280, label: "Snaking Kick", type: "TANKBUSTER" },
        { time: 281, label: "Burst", type: "OTHER" },
        { time: 284, label: "Splattershed", type: "RAIDWIDE" },
        { time: 294, label: "Clone Split", type: "ADD_PHASE" },
        { time: 298, label: "Winged Scourge+Top-tier Slam+Mighty Magic x2", type: "OTHER" },
        { time: 303, label: "Mortal Slayer #1", type: "TANKBUSTER" },
        { time: 304, label: "Double Sabat", type: "STACK" },
        { time: 310, label: "Double Sabat", type: "STACK" },
        { time: 317, label: "Esoteric Finisher", type: "OTHER" },
        { time: 328, label: "Staging", type: "OTHER" },
        { time: 337, label: "Slaughtershed", type: "OTHER" },
        { time: 342, label: "Replication II", type: "RAIDWIDE" },
        { time: 362, label: "Firefall Splash + Scalding Waves", type: "SPREAD" },
        { time: 366, label: "Slaughtershed", type: "OTHER" },
        { time: 370, label: "Mana Burst x3", type: "OTHER" },
        { time: 375, label: "Heavy Slam x2", type: "OTHER" },
        { time: 376, label: "Snaking Kick", type: "TANKBUSTER" },
        { time: 388, label: "Reenactment", type: "OTHER" },
        { time: 394, label: "Netherwrath Near/Far + Reenactment #1", type: "OTHER" },
        { time: 395, label: "Slaughtershed", type: "OTHER" },
        { time: 404, label: "Reenactment #2", type: "OTHER" },
        { time: 421, label: "Mutating Cells", type: "OTHER" },
        { time: 427, label: "Blood Mana", type: "OTHER" },
        { time: 428, label: "Refreshing Overkill", type: "OTHER" },
        { time: 443, label: "Dramatic Lysis", type: "OTHER" },
        { time: 454, label: "Blood Wakening #1", type: "OTHER" },
        { time: 463, label: "Netherworld Near/Far", type: "OTHER" },
        { time: 464, label: "Blood Wakening #2", type: "OTHER" },
        { time: 471, label: "Arcadia Aflame", type: "RAIDWIDE" },
        { time: 481, label: "Double Sabat", type: "STACK" },
        { time: 486, label: "Double Sabat", type: "STACK" },
        { time: 493, label: "Esoteric Finisher", type: "OTHER" },
        { time: 505, label: "Idyllic Dream", type: "OTHER" },
        { time: 513, label: "Staging", type: "OTHER" },
        { time: 527, label: "Twisted Vision Gusher Preview", type: "OTHER" },
        { time: 534, label: "Replication I", type: "RAIDWIDE" },
        { time: 545, label: "Twisted Vision Tether Passes", type: "OTHER" },
        { time: 553, label: "Replication II", type: "RAIDWIDE" },
        { time: 571, label: "Twisted Vision Towers Preview", type: "OTHER" },
        { time: 580, label: "Power Gusher", type: "OTHER" },
        { time: 584, label: "Lindwurm's Meteor", type: "OTHER" },
        { time: 587, label: "Downfall", type: "OTHER" },
        { time: 593, label: "Arcadian Arcanum", type: "OTHER" },
        { time: 600, label: "Twisted Vision Tethers Act", type: "OTHER" },
        { time: 616, label: "Heavy Slam / Mana Burst x2", type: "OTHER" },
        { time: 622, label: "Mana Burst / Heavy Slam x2", type: "OTHER" },
        { time: 626, label: "Heavy Slam / Mana Burst x2", type: "OTHER" },
        { time: 631, label: "Twisted Vision Towers Act + Gusher Preview 2", type: "OTHER" },
        { time: 655, label: "Temporal Curtain", type: "OTHER" },
        { time: 674, label: "Reenactment", type: "OTHER" },
        { time: 682, label: "Twisted Vision Gusher 2", type: "OTHER" },
        { time: 690, label: "Twisted Vision Reenactment 2", type: "OTHER" },
        { time: 691, label: "Power Gusher", type: "OTHER" },
        { time: 701, label: "Reenactment #2", type: "OTHER" },
        { time: 707, label: "Idyllic Dream", type: "OTHER" },
        { time: 715, label: "Double Sabat", type: "STACK" },
        { time: 721, label: "Double Sabat", type: "STACK" },
        { time: 736, label: "Replication I", type: "RAIDWIDE" },
        { time: 750, label: "Arcadian Hell x5", type: "OTHER" },
        { time: 766, label: "Arcadian Hell x9", type: "OTHER" },
        { time: 784, label: "Arcadian Hell x17", type: "OTHER" },
      ],
    },
    // ── Extreme Trials ──────────────────────────────────────
    {
      slug: "ex1",
      name: "EX1 - Worqor Lar Dor",
      patch: "7.0",
      bossName: "Valigarmanda",
      expansion: "Dawntrail",
      tier: "Extreme Trials",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 10, label: "Scratch", type: "TANKBUSTER" },
        { time: 30, label: "Ruinous Blast", type: "RAIDWIDE" },
        { time: 55, label: "Roar of the Tural Vidraal", type: "STACK" },
        { time: 85, label: "Scratch", type: "TANKBUSTER" },
        { time: 115, label: "Ruinous Blast", type: "RAIDWIDE" },
        { time: 150, label: "Roar of the Tural Vidraal", type: "SPREAD" },
        { time: 190, label: "Enrage", type: "ENRAGE" },
      ],
    },
    {
      slug: "ex2",
      name: "EX2 - Everkeep",
      patch: "7.0",
      bossName: "Zoraal Ja",
      expansion: "Dawntrail",
      tier: "Extreme Trials",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 10, label: "Resilient Son", type: "TANKBUSTER" },
        { time: 35, label: "Double-Edged Sword", type: "RAIDWIDE" },
        { time: 65, label: "Duty's Edge", type: "STACK" },
        { time: 100, label: "Resilient Son", type: "TANKBUSTER" },
        { time: 135, label: "Double-Edged Sword", type: "RAIDWIDE" },
        { time: 175, label: "Duty's Edge", type: "SPREAD" },
        { time: 220, label: "Enrage", type: "ENRAGE" },
      ],
    },
    {
      slug: "ex3",
      name: "EX3 - Sphene's Burden",
      patch: "7.1",
      bossName: "Queen Eternal",
      expansion: "Dawntrail",
      tier: "Extreme Trials",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 12, label: "Royal Domain", type: "TANKBUSTER" },
        { time: 38, label: "Eternal Stasis", type: "RAIDWIDE" },
        { time: 68, label: "Crystalline", type: "STACK" },
        { time: 105, label: "Royal Domain", type: "TANKBUSTER" },
        { time: 140, label: "Eternal Stasis", type: "RAIDWIDE" },
        { time: 180, label: "Crystalline", type: "SPREAD" },
        { time: 225, label: "Enrage", type: "ENRAGE" },
      ],
    },
    {
      slug: "ex4",
      name: "EX4 - Recollection",
      patch: "7.2",
      bossName: "Zelenia",
      expansion: "Dawntrail",
      tier: "Extreme Trials",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 10, label: "Knight's Resolve", type: "TANKBUSTER" },
        { time: 35, label: "Queen's Decree", type: "RAIDWIDE" },
        { time: 65, label: "Recollection", type: "STACK" },
        { time: 100, label: "Knight's Resolve", type: "TANKBUSTER" },
        { time: 135, label: "Queen's Decree", type: "RAIDWIDE" },
        { time: 175, label: "Recollection", type: "SPREAD" },
        { time: 220, label: "Enrage", type: "ENRAGE" },
      ],
    },
    {
      slug: "ex5",
      name: "EX5 - Necron's Embrace",
      patch: "7.3",
      bossName: "Necron",
      expansion: "Dawntrail",
      tier: "Extreme Trials",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 12, label: "Void Grasp", type: "TANKBUSTER" },
        { time: 38, label: "Primordial Fear", type: "RAIDWIDE" },
        { time: 70, label: "Embrace of Nihility", type: "STACK" },
        { time: 110, label: "Void Grasp", type: "TANKBUSTER" },
        { time: 150, label: "Primordial Fear", type: "RAIDWIDE" },
        { time: 195, label: "Embrace of Nihility", type: "SPREAD" },
        { time: 245, label: "Enrage", type: "ENRAGE" },
      ],
    },
    {
      slug: "ex6",
      name: "EX6 - Hell on Rails",
      patch: "7.4",
      bossName: "Doomtrain",
      expansion: "Dawntrail",
      tier: "Extreme Trials",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 10, label: "Levin Charge", type: "TANKBUSTER" },
        { time: 35, label: "Phantom Express", type: "RAIDWIDE" },
        { time: 70, label: "Derailment", type: "STACK" },
        { time: 110, label: "Levin Charge", type: "TANKBUSTER" },
        { time: 150, label: "Phantom Express", type: "RAIDWIDE" },
        { time: 195, label: "Derailment", type: "SPREAD" },
        { time: 245, label: "Enrage", type: "ENRAGE" },
      ],
    },
    {
      slug: "ex7",
      name: "EX7 - The Unmaking",
      patch: "7.5",
      bossName: "Enuo",
      expansion: "Dawntrail",
      tier: "Extreme Trials",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 12, label: "Void Sovereign", type: "TANKBUSTER" },
        { time: 40, label: "Unmaking", type: "RAIDWIDE" },
        { time: 75, label: "Nihility", type: "STACK" },
        { time: 115, label: "Void Sovereign", type: "TANKBUSTER" },
        { time: 155, label: "Unmaking", type: "RAIDWIDE" },
        { time: 200, label: "Nihility", type: "SPREAD" },
        { time: 250, label: "Enrage", type: "ENRAGE" },
      ],
    },
    // ── Collaboration Extreme ───────────────────────────────
    {
      slug: "ex-windward",
      name: "The Windward Wilds (Extreme)",
      patch: "7.35",
      bossName: "Guardian Arkveld",
      expansion: "Dawntrail",
      tier: "Extreme Trials",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 15, label: "White Wraith", type: "RAIDWIDE" },
        { time: 45, label: "Arkveld's Fury", type: "TANKBUSTER" },
        { time: 80, label: "Wilds Hunt", type: "STACK" },
        { time: 120, label: "White Wraith", type: "RAIDWIDE" },
        { time: 160, label: "Arkveld's Fury", type: "TANKBUSTER" },
        { time: 200, label: "Wilds Hunt", type: "SPREAD" },
        { time: 250, label: "Enrage", type: "ENRAGE" },
      ],
    },
    // ── Ultimates ────────────────────────────────────────────
    {
      slug: "fru",
      name: "Futures Rewritten (Ultimate)",
      patch: "7.11",
      bossName: "Pandora",
      expansion: "Dawntrail",
      tier: "Ultimate",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 20, label: "Fatebreaker: Burnished Glory", type: "RAIDWIDE" },
        { time: 55, label: "Fatebreaker: Condemnation", type: "TANKBUSTER" },
        { time: 95, label: "Fatebreaker: Fulgent Blade", type: "STACK" },
        { time: 140, label: "Phase Change → Usurper of Frost", type: "OTHER" },
        { time: 160, label: "Usurper: Absolute Zero", type: "RAIDWIDE" },
        { time: 200, label: "Usurper: Ice Tomb", type: "SPREAD" },
        { time: 245, label: "Usurper: Diamond Dust", type: "RAIDWIDE" },
        { time: 295, label: "Phase Change → Oracle of Darkness", type: "OTHER" },
        { time: 315, label: "Oracle: Dark Pulse", type: "RAIDWIDE" },
        { time: 355, label: "Oracle: Nightfall", type: "TANKBUSTER" },
        { time: 400, label: "Oracle: Akh Morn", type: "STACK" },
        { time: 460, label: "Phase Change → Enter the Dragon", type: "OTHER" },
        { time: 480, label: "Dragon: Dual Akh Morn", type: "RAIDWIDE" },
        { time: 540, label: "Dragon: Polarizing Strikes", type: "TANKBUSTER" },
        { time: 600, label: "Phase Change → Pandora", type: "OTHER" },
        { time: 620, label: "Pandora: Paradise Regained", type: "RAIDWIDE" },
        { time: 680, label: "Pandora: Fulgent Blade Exa", type: "STACK" },
        { time: 750, label: "Pandora: Paradise Lost", type: "ENRAGE" },
      ],
    },
    {
      slug: "dmu",
      name: "Dancing Mad (Ultimate)",
      patch: "7.51",
      bossName: "Kefka",
      expansion: "Dawntrail",
      tier: "Ultimate",
      timestamps: [
        { time: 0, label: "Pull", type: "OTHER" },
        { time: 15, label: "Kefka: Hyperdrive", type: "RAIDWIDE" },
        { time: 50, label: "Kefka: Havoc", type: "TANKBUSTER" },
        { time: 90, label: "Kefka: Trickster", type: "STACK" },
        { time: 140, label: "Phase Change → God Kefka", type: "OTHER" },
        { time: 160, label: "God Kefka: Havoc", type: "RAIDWIDE" },
        { time: 210, label: "God Kefka: Hyperdrive", type: "TANKBUSTER" },
        { time: 270, label: "God Kefka: Timely Teleport", type: "SPREAD" },
        { time: 330, label: "God Kefka: Havoc", type: "RAIDWIDE" },
        { time: 400, label: "God Kefka: Hyperdrive", type: "TANKBUSTER" },
        { time: 480, label: "Dancing Mad", type: "ENRAGE" },
      ],
    },
  ];

  for (const fight of fights) {
    await prisma.fight.upsert({
      where: { slug: fight.slug },
      update: {
        name: fight.name,
        patch: fight.patch,
        bossName: fight.bossName,
        expansion: fight.expansion,
        tier: fight.tier,
        timestamps: fight.timestamps,
      },
      create: fight as any,
    });
  }

  console.log("Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
